# Generated by Django 3.2.12 on 2023-04-10 20:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('otp_static', '0002_throttling'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staticdevice',
            options={'verbose_name': 'static device', 'verbose_name_plural': 'static devices'},
        ),
        migrations.AlterModelOptions(
            name='statictoken',
            options={'verbose_name': 'static token', 'verbose_name_plural': 'static tokens'},
        ),
        migrations.AlterField(
            model_name='staticdevice',
            name='confirmed',
            field=models.BooleanField(default=True, help_text='Is this device ready for use?', verbose_name='confirmed'),
        ),
        migrations.AlterField(
            model_name='staticdevice',
            name='name',
            field=models.CharField(help_text='The human-readable name of this device.', max_length=64, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='staticdevice',
            name='throttling_failure_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of successive failed attempts.', verbose_name='throttling failure count'),
        ),
        migrations.AlterField(
            model_name='staticdevice',
            name='throttling_failure_timestamp',
            field=models.DateTimeField(blank=True, default=None, help_text='A timestamp of the last failed verification attempt. Null if last attempt succeeded.', null=True, verbose_name='throttling failure timestamp'),
        ),
        migrations.AlterField(
            model_name='staticdevice',
            name='user',
            field=models.ForeignKey(help_text='The user that this device belongs to.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='statictoken',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_set', to='otp_static.staticdevice', verbose_name='device'),
        ),
        migrations.AlterField(
            model_name='statictoken',
            name='token',
            field=models.CharField(db_index=True, max_length=16, verbose_name='token'),
        ),
    ]
