# Generated by Django 3.2.12 on 2023-04-10 20:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_otp.plugins.otp_totp.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('otp_totp', '0002_auto_20190420_0723'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='totpdevice',
            options={'verbose_name': 'TOTP device', 'verbose_name_plural': 'TOTP devices'},
        ),
        migrations.AlterField(
            model_name='totpdevice',
            name='confirmed',
            field=models.BooleanField(default=True, help_text='Is this device ready for use?', verbose_name='confirmed'),
        ),
        migrations.AlterField(
            model_name='totpdevice',
            name='digits',
            field=models.PositiveSmallIntegerField(choices=[(6, 6), (8, 8)], default=6, help_text='The number of digits to expect in a token.', verbose_name='digits'),
        ),
        migrations.AlterField(
            model_name='totpdevice',
            name='drift',
            field=models.SmallIntegerField(default=0, help_text='The number of time steps the prover is known to deviate from our clock.', verbose_name='drift'),
        ),
        migrations.AlterField(
            model_name='totpdevice',
            name='key',
            field=models.CharField(default=django_otp.plugins.otp_totp.models.default_key, help_text='A hex-encoded secret key of up to 40 bytes.', max_length=80, validators=[django_otp.plugins.otp_totp.models.key_validator], verbose_name='key'),
        ),
        migrations.AlterField(
            model_name='totpdevice',
            name='last_t',
            field=models.BigIntegerField(default=-1, help_text='The t value of the latest verified token. The next token must be at a higher time step.', verbose_name='last time'),
        ),
        migrations.AlterField(
            model_name='totpdevice',
            name='name',
            field=models.CharField(help_text='The human-readable name of this device.', max_length=64, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='totpdevice',
            name='step',
            field=models.PositiveSmallIntegerField(default=30, help_text='The time step in seconds.', verbose_name='step'),
        ),
        migrations.AlterField(
            model_name='totpdevice',
            name='t0',
            field=models.BigIntegerField(default=0, help_text='The Unix time at which to begin counting steps.', verbose_name='time'),
        ),
        migrations.AlterField(
            model_name='totpdevice',
            name='throttling_failure_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of successive failed attempts.', verbose_name='throttling failure count'),
        ),
        migrations.AlterField(
            model_name='totpdevice',
            name='throttling_failure_timestamp',
            field=models.DateTimeField(blank=True, default=None, help_text='A timestamp of the last failed verification attempt. Null if last attempt succeeded.', null=True, verbose_name='throttling failure timestamp'),
        ),
        migrations.AlterField(
            model_name='totpdevice',
            name='tolerance',
            field=models.PositiveSmallIntegerField(default=1, help_text='The number of time steps in the past or future to allow.', verbose_name='tolerance'),
        ),
        migrations.AlterField(
            model_name='totpdevice',
            name='user',
            field=models.ForeignKey(help_text='The user that this device belongs to.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
